---
- name: Ansible playbook to provision components
  hosts: all #"{{ dynamic_group | default('ubuntu-sdk-slave-servers') }}"
  become: yes
  gather_facts: no

  roles:
    - { role: envi_setup, tags: [ 'envi_setup' ] }

